/**
/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('events').del()
  await knex('events').insert([
    {
      id: 1,
      trip_id: 1,
      created_by: 1,
      date: '2024-07-02',
      start_time: '04:00pm',
      end_time: '06:00pm',
      description: 'Meet at Zebra Cafe',
      notes:
        'Bring sunblock and sunglasses. The cafe has a great outdoor seating area where we can enjoy the sunset.',
      location: '123 Jump Street',
      type: 'event',
    },
    {
      id: 2,
      trip_id: 1,
      created_by: 1,
      date: '2024-07-01',
      start_time: '07:00am',
      end_time: '09:00am',
      description: 'Flight to New York',
      notes:
        'Check in at least 2 hours before the flight. Bring your passport and travel documents.',
      location: 'JFK Airport',
      type: 'flight',
    },
    {
      id: 3,
      trip_id: 1,
      created_by: 1,
      date: '2024-07-01',
      start_time: '08:00pm',
      end_time: '10:00pm',
      description: 'Check-in at Hotel',
      notes:
        'Present your booking confirmation at the reception. The hotel offers complimentary breakfast.',
      location: 'Chelsea Hotel',
      type: 'accommodation',
    },
    {
      id: 4,
      trip_id: 2,
      created_by: 2,
      date: '2024-08-03',
      start_time: '10:00am',
      end_time: '12:00pm',
      description: 'Museum Visit',
      notes:
        'Bring a camera for some great photo opportunities. The museum has a special exhibit on ancient artifacts.',
      location: 'Main Museum',
      type: 'event',
    },
    {
      id: 5,
      trip_id: 2,
      created_by: 2,
      date: '2024-08-02',
      start_time: '06:00pm',
      end_time: '08:00pm',
      description: 'Flight to Tokyo',
      notes:
        'Arrive early for security checks. Bring your boarding pass and travel documents.',
      location: 'Narita Airport',
      type: 'flight',
    },
    {
      id: 6,
      trip_id: 2,
      created_by: 2,
      date: '2024-08-02',
      start_time: '09:00pm',
      end_time: '11:00pm',
      description: 'Check-in at Hotel',
      notes:
        'Enjoy the welcome drink upon arrival. The hotel offers various recreational activities.',
      location: 'Hotel Tokyo',
      type: 'accommodation',
    },
    {
      id: 7,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-11',
      start_time: '06:00am',
      end_time: '08:00am',
      description: 'Climb the Eiffel Tower',
      notes:
        'Bring water, a hat, and a light jacket. The tower offers stunning views of Paris from the top.',
      location: 'Eiffel Tower',
      type: 'event',
    },
    {
      id: 8,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-10',
      start_time: '11:00am',
      end_time: '01:00pm',
      description: 'Flight to Paris',
      notes:
        'Ensure your carry-on is within the allowed size. The flight includes a meal service.',
      location: 'Charles de Gaulle Airport',
      type: 'flight',
    },
    {
      id: 9,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-10',
      start_time: '03:00pm',
      end_time: '05:00pm',
      description: 'Check-in at Boutique Hotel',
      notes:
        'Welcome drinks provided. The hotel has an excellent spa and wellness center.',
      location: 'Boutique Hotel',
      type: 'accommodation',
    },
    {
      id: 13,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-11',
      start_time: '09:00am',
      end_time: '11:00am',
      description: 'Visit the Louvre',
      notes: 'Meet at the main entrance. Guided tour starts at 9:30am.',
      location: 'Louvre Museum, Paris',
      type: 'event',
    },
    {
      id: 14,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-11',
      start_time: '02:00pm',
      end_time: '04:00pm',
      description: 'Lunch at Eiffel Tower',
      notes:
        'Lunch at the restaurant on the second floor of the Eiffel Tower. Reservation under "Craig".',
      location: 'Eiffel Tower, Paris',
      type: 'event',
    },
    {
      id: 15,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-13',
      start_time: '10:00am',
      end_time: '12:00pm',
      description: 'Seine River Cruise',
      notes:
        'Boat departs from the dock near Notre Dame. Arrive 15 minutes early.',
      location: 'Seine River, Paris',
      type: 'event',
    },
    {
      id: 16,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-11',
      start_time: '06:00pm',
      end_time: '08:00pm',
      description: 'Dinner at Le Jules Verne',
      notes: 'Reservation for 6:00pm. Dress code is semi-formal.',
      location: 'Le Jules Verne, Paris',
      type: 'event',
    },
    {
      id: 17,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-17',
      start_time: '11:00am',
      end_time: '01:00pm',
      description: 'Visit to Montmartre',
      notes:
        'Walking tour of the Montmartre district. Meet at the Sacré-Cœur Basilica.',
      location: 'Montmartre, Paris',
      type: 'event',
    },
    {
      id: 18,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-19',
      start_time: '03:00pm',
      end_time: '05:00pm',
      description: 'Wine Tasting in Saint-Germain',
      notes: 'Tasting includes a selection of French wines and cheeses.',
      location: 'Saint-Germain, Paris',
      type: 'event',
    },
    {
      id: 19,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-21',
      start_time: '09:00am',
      end_time: '11:00am',
      description: 'Shopping on Champs-Élysées',
      notes:
        'Explore the luxury boutiques and stores along the Champs-Élysées.',
      location: 'Champs-Élysées, Paris',
      type: 'event',
    },
    {
      id: 20,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-23',
      start_time: '01:00pm',
      end_time: '03:00pm',
      description: 'Lunch at Café de Flore',
      notes: 'Lunch at one of the oldest and most iconic cafes in Paris.',
      location: 'Café de Flore, Paris',
      type: 'event',
    },
    {
      id: 21,
      trip_id: 3,
      created_by: 3,
      date: '2024-10-25',
      start_time: '08:00am',
      end_time: '10:00am',
      description: 'Breakfast at Angelina',
      notes:
        'Famous for their hot chocolate and pastries. Arrive early to avoid the queue.',
      location: 'Angelina, Paris',
      type: 'event',
    },
    {
      id: 10,
      trip_id: 4,
      created_by: 4,
      date: '2024-12-16',
      start_time: '01:00pm',
      end_time: '03:00pm',
      description: 'Wine Tasting',
      notes:
        'Bring ID to participate in the wine tasting. Sample a variety of wines produced at the vineyard.',
      location: 'Vineyard',
      type: 'event',
    },
    {
      id: 11,
      trip_id: 4,
      created_by: 4,
      date: '2024-12-15',
      start_time: '05:00pm',
      end_time: '07:00pm',
      description: 'Flight to Rome',
      notes:
        'Check-in online to save time. Enjoy complimentary snacks and beverages during the flight.',
      location: 'Fiumicino Airport',
      type: 'flight',
    },
    {
      id: 12,
      trip_id: 4,
      created_by: 4,
      date: '2024-12-15',
      start_time: '07:00pm',
      end_time: '09:00pm',
      description: 'Check-in at Colosseum Hotel',
      notes:
        'Enjoy the complimentary breakfast and city views from your room. The hotel is located near popular tourist attractions.',
      location: 'Colosseum Hotel',
      type: 'accommodation',
    },
  ])
}
